title: Learn Coding
author: Tom Hutcheson
email: t.hutcheson92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My journey through learning to code

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
